import localFont from "next/font/local";
import "./globals.css";
export const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
export const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
export const graphikRegular = localFont({
  src: "../app/fonts/Graphik-Font-Family/GraphikRegular.otf",
  variable: "--font-graphik-regular",
  weight: "100 900",
});
export const metadata = {
  title: "Dream AI",
  description: "Generated by Ali007",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${graphikRegular.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
